# Generated by Django 3.1.3 on 2020-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=15, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=15, verbose_name='title'),
        ),
    ]
