# Generated by Django 3.1.3 on 2020-12-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='transaction',
            new_name='order_id',
        ),
    ]
