# Generated by Django 3.1.3 on 2020-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201203_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recepientName',
            field=models.CharField(default='', max_length=60, null=True),
        ),
    ]
